### ISSUE TITLE
SFTP w/ private key fails

### ISSUE THREAD

**Issue by 1xPdd** [mickael-kerjean/nuage#89]
Hi,

Great project!

I'm having a bit of trouble logging in via SFTP while using an RSA private key. The compose file is pretty vanilla:
```
version: '2'
services:
  app:
    container_name: nuage
    image: machines/nuage
    restart: unless-stopped
    volumes:
     - ./config_client.js:/app/config_client.js
#     - ./config_server.js:/app/config_server.js
    environment:
     - SECRET_KEY=[secret_key]
     - TRANSCODER_URL=http://transcode:8335
    ports:
    - "8334:8334"

  transcode:
    container_name: nuage_transcode
    image: machines/nuage_transcode
    restart: unless-stopped
```

WebDav + Nextcloud works but SFTP fails with "Cannot Parse privateKey. Unsupported key format." In the logs there is a "status=401" error. For the RSA key, I just have: /home/[me]/.ssh/id_rsa, which I can open in Firefox. Nor sure where the 401 is coming from.

Thanks!
